version: 0.2

phases:
  pre_build:
    commands:
      - |
        if [ -n "$COMMIT_ID" ]; then
          echo Checking out to celery_${ENVIRONMENT}_latest tag...
          git checkout tags/celery_${ENVIRONMENT}_latest
        fi
  build:
    commands:
      - echo Deployment started on `date`
      - bash ./.codepipeline/deploy-service.sh --SERVICE celery --RESOURCE_PREFIX ${RESOURCE_PREFIX:-eas-app}
