version: 0.2

phases:
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap
      - cd $API_DIR && . $VENV_API/bin/activate && make test
  post_build:
    commands:
      - echo "No post build commands"
