version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking out to celery_${ENVIRONMENT}_latest tag...
      - git checkout tags/celery_${ENVIRONMENT}_latest
  build:
    commands:
      - echo Deployment started on `date`
      - bash ./.codepipeline/deploy-service.sh --SERVICE celery --RESOURCE_PREFIX $ECR_RESOURCE_PREFIX
