# This .dist file will be autogenerated to version.py by the Makefile
# Consumers of version.py should not rely upon importing being successful

git_commit = "$GIT_COMMIT"
time = "$TIME"  # ISO8601
app_version = "$APP_VERSION"
base_version = "$BASE_VERSION"
