name: on-pr-into-main

env:
  PYTHON_VERSION: 3.9

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Verify Docker
        run: |
          docker --version || echo 'Could not find docker engine'
          docker compose version || echo 'Could not find docker compose'

      - name: Install and upgrade pre-requisites
        run: |
          python3.9 -m pip install --upgrade pip wheel setuptools
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libssl-dev

      - name: Launch a postgres instance
        run: |
          docker compose -f docker-compose-tests.yml up --detach pg

      - name: Bootstrap Python app and run tests
        run: |
          export ENVIRONMENT='local'
          export DANGEROUS_SALT='dev-notify-salt'
          export SECRET_KEY='dev-notify-secret-key'
          export ENCRYPTION_DANGEROUS_SALT='dev-notify-salt'
          export ENCRYPTION_SECRET_KEY='dev-notify-secret-key'
          export ADMIN_CLIENT_SECRET='dev-notify-secret-key'
          export FLASK_APP=application.py
          export TEST_RDS_HOST=localhost
          export TEST_RDS_USER=postgres
          export TEST_RDS_PASSWORD=root
          export TEST_RDS_PORT=5432
          set -eu
          make bootstrap-for-tests
          make test
